### ISSUE TITLE
Compile in Python 2.4

### ISSUE THREAD

**Issue by andrespineda** [digidotcom/xbgw-app#3]
Hi,
I have quite a few ConnectPort X4s with lots of memory, but they only operate on Python 2.4.
I am not a Python Guru, so I am asking if it is possible to make this module compile on Python 2.4 if I spend the time to go through and make the necessary changes?

In other words, other than syntax issues, is there a fundamental reason that this will not be able to be converted to compile under Python 2.4 that I am not aware of?
Thanks in advance for your consideration.

**Comment by mikewadsten** [comment]
Hi @andrespineda,

The main reason I can think of for why this code may not work under Python 2.4, beyond syntax issues (like the use of context managers) or standard library changes, is compatibility of the PyPubSub library. Python 2.4 was already old when we started development of the XBGW app code (2.4.x support was ended by the PSF in _2008_), so I think it's unlikely that there even exists a version of PyPubSub compatible with Python 2.4.

Our recommended approach for developing an application on the X4 would be DIA. https://www.digi.com/resources/documentation/digidocs/90001537/default.htm#containers/cont_dia.htm

If you have any questions about DIA please contact Digi tech support.

**Comment by andrespineda** [comment]
Thank you very much! I will give up on xbgw and certainly pursue the DIA approach.
